---
:credentials:
  :username: max708
  :password: TP9i3x6EtbQGbDqjbMA5
:screenshots_folder: "/tmp"
:browsers:
- :browser: IE
  :browser_version: 11.0
  :os: Windows
  :os_version: 7
- :browser: IE
  :browser_version: 10.0
  :os: Windows
  :os_version: 7
